---
title: "Project Proposal"
author: "Wesley Lim"
date: "2022-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Final Project Proposal/Rubric

-   Subject to change as project progresses with instructor approval

### Learning Goals

-   Gain a basic understanding of Python and its function in data science.
-   Construct a visual/graphical presentation of selected data sets.
-   Work with 2-3 different types of data sets (quantitative vs quantitative).
-   Utilize PANDAS package in Python for data analysis.

### Data set(s)

-   Plastic Pollution (<https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-01-26/readme.md>)
-   Wealth and Income (extra) (<https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-02-09/readme.md>)

### Project

-   Plastic Pollution
    -   This data set contains data about global plastic pollution in the years 2019-2020. The data can be categorized by plastic type, country of cleanup, and source of plastic. While the data isn't necessarily an accurate representative of plastic pollution, however it can give a glimpse into the situation given increasing environmental concerns. The data set can be loaded via:

```{plastic pollution}
    install.packages("tidytuesdayR")
    tuesdata_A <- tidytuesdayR::tt_load('2021-02-09')
```

-   Wealth and Income (extra)
    -   This data set deals with racial wealth inequality in America and contains summary-level individual smaller data sets. The data can be presented by presenting wealth via percentage home ownerships, total family wealth, student debt loans, income distributions, etc.The data set can be loaded via:

```{Wealth and income}
    install.packages("tidytuesdayR")
    tuesdata_B <- tidytuesdayR::tt_load('2021-01-26')
```

-   Project objectives
    -   Load tidyverse data and convert to usable format for Python.
    -   Load PANDAS in Python and any other required packages.
    -   Transform data into a cleaner or tidier format in Python
    -   Perform statistical tests to best present data in an objective perspective.
    -   Visualize data sets and results of statistical tests
